### ISSUE TITLE
Куда отправить на кофе?

### ISSUE THREAD

**Issue by Fi1osof** [balance-platform/phx_keycloak#1]
Спасибо большое! Ваша библиотека сильно помогла! Правда пришлось в феникс прописать сессии хранилище в куки, так как никакое иное не использовалось, а без него не работало, но все равно получилось запустить и это здорово!
Куда можно на кофе копеечку отправить?

**Comment by sofakingworld** [comment]
@Fi1osof Спасибо на добром слове) Этого достаточно)

Если у вас есть какие-то доработки по библиотеке, мы их с радостью рассмотрим и добавим в master, это будет лучшим вкладом)

**Comment by Fi1osof** [comment]
@sofakingworld к сожалению, я в элексире совсем плох. Просто у нас на проекте он используется в одном из микросервисов и приходится иногда допиливать по мере сил. Так что никакой МР не смогу отправить, к сожалению :-(
А вам удачи и еще раз огромное спасибо!
